import streamlit as st
import datetime 
import requests
import sys

BASE_URL = "http://localhost:8000"

st.set_page_config(page_title="AI Trip Planner", page_icon=":airplane:", layout="centered", initial_sidebar_state="auto",)


st.title("AI Trip Planner :airplane:")

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

st.header("Plan Your Trip with AI")

with st.form(key="query_form",clear_on_submit=True):
    submit_button =st.form_submit_button("Submit")
    user_input =st.text_input("Enter your travel query:", placeholder="e.g. Where should I go for a vacation?")

if submit_button and user_input.strip():
    try:
        with st.spinner("Processing your request..."):
            # Send the user input to the backend API
            payload = {"question": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)
        if response.status_code == 200:
            answer = response.json().get("answer", "No answer found.")
            markdown_content = f"""### AI Travel plan:
            # **Generated on:** {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
            # **Created by:** AI Trip Planner made by [Harmish Zala]
            # **User Query:** {user_input}

            ---
            \n\n{answer}

            ---
            **Note:** This plan is generated by an AI model and may not include all the latest information. Please verify details before making any bookings or travel arrangements.
            """
            st.markdown(markdown_content)
        else:
            st.error("Bot failed to respond. Please try again later." + response.text)
    except Exception as e:
        raise f"Error occurred while processing your request: {e}"
         